// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { supabasePoolerCompatUrl } from "./prisma/poolerCompat";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: supabasePoolerCompatUrl(process.env.DIRECT_URL ?? process.env.DATABASE_URL),
  },
});
